services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - jbdatahubui
      - jbdatahub
    restart: unless-stopped
    networks:
      - app-network

  jbdatahubui:
    build:
      context: ./jbDataHubUI
      dockerfile: Dockerfile
    container_name: jbdatahubui
    restart: unless-stopped
    networks:
      - app-network

  jbdatahub:
    build:
      context: ./jbDataHub
      dockerfile: Dockerfile
    container_name: jbdatahub
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge