services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - jbdatahubui
    restart: unless-stopped
    networks:
      - app-network

  jbdatahubui:
    build:
      context: ./ui/jbdatahub
      dockerfile: Dockerfile
    container_name: jbdatahubui
    restart: unless-stopped
    networks:
      - app-network

  jbdatahub-blue:
    build:
      context: ./server/jbdatahub
      dockerfile: Dockerfile
    container_name: jbdatahub-blue
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  jbdatahub-green:
    build:
      context: ./server/jbdatahub
      dockerfile: Dockerfile
    container_name: jbdatahub-green
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
